using PcfManager.Models;
using Microsoft.EntityFrameworkCore;

namespace PcfManager.Data;

public class ApplicationDbContext : DbContext
{
    private readonly IWebHostEnvironment _env;

    // public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) { }
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options, IWebHostEnvironment env) : base(options)
    {


        _env = env;

        if (_env.IsProduction())
        {
            //throw new InvalidOperationException("Migrations cannot run against the production database.");
        }
        // Disable EF Tracking globally for this DbContext
        ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        if (!_env.IsProduction())
        {
            // Enable sensitive data logging only in non-production environments
            optionsBuilder.EnableSensitiveDataLogging();
        }
    }

    public DbSet<User> Users { get; set; }
    public DbSet<Role> Roles { get; set; }
    //public DbSet<Rep> Reps { get; set; }
    public DbSet<UserHierarchy> UserHierarchies { get; set; }
    public DbSet<ConsolidatedCustomer> ConsolidatedCustomers { get; set; }
    public DbSet<UserCustomerAccess> UserCustomerAccesses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Map ConsolidatedCustomer to existing table
        modelBuilder.Entity<ConsolidatedCustomer>()
            .HasKey(cc => new { cc.CustNum, cc.CustSeq }); // Composite key

        // Configure UserId as an identity column
        modelBuilder.Entity<User>()
            .Property(u => u.UserId)
            .ValueGeneratedOnAdd(); // Indicates that UserId is auto-generated by the database


        // Define Role relationship
        modelBuilder.Entity<User>().HasOne(u => u.Role)
      .WithMany(r => r.Users)
        .HasForeignKey(u => u.RoleId);


        // Configure UserCustomerAccess relationships
        modelBuilder.Entity<UserCustomerAccess>()
            .HasKey(uca => new { uca.Site, uca.UserId, uca.CustNum, uca.CustSeq });

        modelBuilder.Entity<UserCustomerAccess>()
            .HasOne(uca => uca.User)
            .WithMany(u => u.CustomerAccesses)
            .HasForeignKey(uca => uca.UserId);

        modelBuilder.Entity<UserCustomerAccess>()
            .HasOne(uca => uca.Customer)
            .WithMany(c => c.UserCustomerAccesses)
            .HasForeignKey(uca => new { uca.CustNum, uca.CustSeq });




        // Seed initial roles
        modelBuilder.Entity<Role>().HasData(
            new Role { RoleId = 1, RoleName = "Administrator" },
            new Role { RoleId = 2, RoleName = "Executive" },
            new Role { RoleId = 3, RoleName = "Director" },
            new Role { RoleId = 4, RoleName = "Sales Manager" },
            new Role { RoleId = 5, RoleName = "Sales Rep" }
        );



        modelBuilder.Entity<User>().HasData(
            new User { UserId = 1, DomainId = "willit2@chapinmfg.com", Username = "admin", RoleId = 1 },
            new User { UserId = 2, DomainId = "ccoogan@chapinmfg.com", Username = "executive", RoleId = 2 }
        );



        // Seed Customers

        // Seed ConsolidatedCustomer
        modelBuilder.Entity<ConsolidatedCustomer>().HasData(
            new ConsolidatedCustomer { CustNum = "LILBOY", CustSeq = 0 }
        );


        // Seed UserCustomerAccess
        // modelBuilder.Entity<UserCustomerAccess>().HasData(
        //    new UserCustomerAccess
        //     {
        //         UserId = 1, CustNum = "LILBOY", CustSeq = 0, Site="BAT"
        //     }
        //  );



        // Configure UserHierarchy relationships
        modelBuilder.Entity<UserHierarchy>()
            .HasKey(uh => new { uh.ManagerId, uh.SubordinateId });

        modelBuilder.Entity<UserHierarchy>()
            .HasOne(uh => uh.Manager)
            .WithMany(u => u.ManagedUsers)
            .HasForeignKey(uh => uh.ManagerId)
            .OnDelete(DeleteBehavior.Restrict); // Prevent cascading deletes

        modelBuilder.Entity<UserHierarchy>()
            .HasOne(uh => uh.Subordinate)
            .WithMany(u => u.ReportsTo)
            .HasForeignKey(uh => uh.SubordinateId)
            .OnDelete(DeleteBehavior.Restrict);






    }
}