namespace PcfManager.Models;

public class ItemEntityFull
{
    public string? site_ref { get; } = null!;
    public string? item { get; } = null!;
    public string? description { get; }
    public decimal qty_allocjob { get; }
    public string? u_m { get; }
    public short lead_time { get; }
    public decimal lot_size { get; }
    public decimal qty_used_ytd { get; }
    public decimal qty_mfg_ytd { get; }
    public string? abc_code { get; }
    public string? drawing_nbr { get; }
    public string? product_code { get; }
    public string? p_m_t_code { get; }
    public string? cost_method { get; }
    public decimal lst_lot_size { get; }
    public decimal unit_cost { get; }
    public decimal lst_u_cost { get; }
    public decimal avg_u_cost { get; }
    public string? job { get; }
    public short suffix { get; }
    public byte stocked { get; }
    public string? matl_type { get; }
    public string? family_code { get; }
    public byte low_level { get; }
    public DateTime last_inv { get; }
    public short days_supply { get; }
    public decimal order_min { get; }
    public decimal order_mult { get; }
    public string? plan_code { get; }
    public byte mps_flag { get; }
    public byte accept_req { get; }
    public DateTime change_date { get; }
    public string? revision { get; }
    public byte phantom_flag { get; }
    public byte plan_flag { get; }
    public short paper_time { get; }
    public short dock_time { get; }
    public decimal asm_setup { get; }
    public decimal asm_run { get; }
    public decimal asm_matl { get; }
    public decimal asm_tool { get; }
    public decimal asm_fixture { get; }
    public decimal asm_other { get; }
    public decimal asm_fixed { get; }
    public decimal asm_var { get; }
    public decimal asm_outside { get; }
    public decimal comp_setup { get; }
    public decimal comp_run { get; }
    public decimal comp_matl { get; }
    public decimal comp_tool { get; }
    public decimal comp_fixture { get; }
    public decimal comp_other { get; }
    public decimal comp_fixed { get; }
    public decimal comp_var { get; }
    public decimal comp_outside { get; }
    public decimal sub_matl { get; }
    public decimal shrink_fact { get; }
    public string? alt_item { get; }
    public decimal unit_weight { get; }
    public string? weight_units { get; }
    public string? charfld4 { get; }
    public decimal cur_u_cost { get; }
    public string? feat_type { get; }
    public decimal var_lead { get; }
    public string? feat_str { get; }
    public short next_config { get; }
    public string? feat_templ { get; }
    public byte backflush { get; }
    public string? charfld1 { get; }
    public string? charfld2 { get; }
    public string? charfld3 { get; }
    public decimal decifld1 { get; }
    public decimal decifld2 { get; }
    public decimal decifld3 { get; }
    public byte logifld { get; }
    public DateTime datefld { get; }
    public byte track_ecn { get; }
    public decimal u_ws_price { get; }
    public string? comm_code { get; }
    public string? origin { get; }
    public decimal unit_mat_cost { get; }
    public decimal unit_duty_cost { get; }
    public decimal unit_freight_cost { get; }
    public decimal unit_brokerage_cost { get; }
    public decimal cur_mat_cost { get; }
    public decimal cur_duty_cost { get; }
    public decimal cur_freight_cost { get; }
    public decimal cur_brokerage_cost { get; }
    public string? tax_code1 { get; }
    public string? tax_code2 { get; }
    public string? bflush_loc { get; }
    public byte reservable { get; }
    public short shelf_life { get; }
    public string? lot_prefix { get; }
    public string? serial_prefix { get; }
    public byte serial_length { get; }
    public string? issue_by { get; }
    public byte serial_tracked { get; }
    public byte lot_tracked { get; }
    public string? cost_type { get; }
    public decimal matl_cost { get; }
    public decimal lbr_cost { get; }
    public decimal fovhd_cost { get; }
    public decimal vovhd_cost { get; }
    public decimal out_cost { get; }
    public decimal cur_matl_cost { get; }
    public decimal cur_lbr_cost { get; }
    public decimal cur_fovhd_cost { get; }
    public decimal cur_vovhd_cost { get; }
    public decimal cur_out_cost { get; }
    public decimal avg_matl_cost { get; }
    public decimal avg_lbr_cost { get; }
    public decimal avg_fovhd_cost { get; }
    public decimal avg_vovhd_cost { get; }
    public decimal avg_out_cost { get; }
    public string? prod_type { get; }
    public decimal rate_per_day { get; }
    public short mps_plan_fence { get; }
    public byte pass_req { get; }
    public byte lot_gen_exp { get; }
    public string? supply_site { get; }
    public string? prod_mix { get; }
    public string? stat { get; }
    public string? status_chg_user_code { get; }
    public DateTime chg_date { get; }
    public string? reason_code { get; }
    public string? supply_whse { get; }
    public short due_period { get; }
    public decimal order_max { get; }
    public byte mrp_part { get; }
    public byte infinite_part { get; }
    public byte NoteExistsFlag { get; }
    public DateTime RecordDate { get; }
    public Guid RowPointer { get; }
    public decimal supply_tolerance_hrs { get; }
    public short exp_lead_time { get; }
    public decimal var_exp_lead { get; }
    public string? buyer { get; }
    public byte order_configurable { get; }
    public byte job_configurable { get; }
    public string? cfg_model { get; }
    public string? auto_job { get; }
    public string? setupgroup { get; }
    public string? CreatedBy { get; }
    public string? UpdatedBy { get; }
    public DateTime CreateDate { get; }
    public byte InWorkflow { get; }
    public byte mfg_supply_switching_active { get; }
    public short time_fence_rule { get; }
    public double time_fence_value { get; }
    public DateTime earliest_planned_po_receipt { get; }
    public byte use_reorder_point { get; }
    public decimal reorder_point { get; }
    public decimal fixed_order_qty { get; }
    public decimal unit_insurance_cost { get; }
    public decimal unit_loc_frt_cost { get; }
    public decimal cur_insurance_cost { get; }
    public decimal cur_loc_frt_cost { get; }
    public byte tax_free_matl { get; }
    public short tax_free_days { get; }
    public decimal safety_stock_percent { get; }
    public string? tariff_classification { get; }
    public DateTime lowdate { get; }
    public string? rcpt_rqmt { get; }
    public byte active_for_data_integration { get; }
    public decimal rcvd_over_po_qty_tolerance { get; }
    public decimal rcvd_under_po_qty_tolerance { get; }
    public byte include_in_net_change_planning { get; }
    public byte kit { get; }
    public byte print_kit_components { get; }
    public short safety_stock_rule { get; }
    public byte show_in_drop_down_list { get; }
    public byte controlled_by_external_ics { get; }
    public decimal inventory_ucl_tolerance { get; }
    public decimal inventory_lcl_tolerance { get; }
    public string? separation_attribute { get; }
    public double batch_release_attribute1 { get; }
    public double batch_release_attribute2 { get; }
    public double batch_release_attribute3 { get; }
    public byte[] picture { get; }
    public byte active_for_customer_portal { get; }
    public byte featured { get; }
    public byte top_seller { get; }
    public string? overview { get; }
    public byte preassign_lots { get; }
    public byte preassign_serials { get; }
    public string? attr_group { get; }
    public string? dimension_group { get; }
    public string? lot_attr_group { get; }
    public byte track_pieces { get; }
    public DateTime bom_last_import_date { get; }
    public byte save_current_rev_upon_bom_import { get; }
    public string? nafta_pref_crit { get; }
    public byte subject_to_nafta_rvc { get; }
    public byte producer { get; }
    public string? nafta_country_of_origin { get; }
    public byte must_use_future_rcpts_before_pln { get; }
    public string? portal_pricing_site { get; }
    public byte portal_pricing_enabled { get; }
    public byte subject_to_excise_tax { get; }
    public decimal excise_tax_percent { get; }
    public decimal freight_amt { get; }
    public byte item_content { get; }
    public DateTime estimated_matl_use_up_date { get; }
    public DateTime last_matl_use_up_report_date { get; }
    public string? uf_addtl_spec1 { get; }
    public string? uf_addtl_spec2 { get; }
    public string? uf_addtl_spec3 { get; }
    public string? uf_addtl_spec4 { get; }
    public string? uf_item_brand { get; }
    public decimal uf_mfg_lytd { get; }
    public decimal uf_purch_lytd { get; }
    public decimal uf_sold_lytd { get; }
    public decimal uf_used_lytd { get; }
    public string? uf_qual_spec { get; }
    public string? uf_mplan_code { get; }
    public string? uf_item { get; }
    public decimal uf_part_wt { get; }
    public decimal PP_length_linear_dimension { get; }
    public decimal PP_width_linear_dimension { get; }
    public decimal PP_height_linear_dimension { get; }
    public string? PP_linear_dimension_u_m { get; }
    public decimal PP_density { get; }
    public string? PP_density_u_m { get; }
    public decimal PP_area { get; }
    public string? PP_area_u_m { get; }
    public decimal PP_bulk_mass { get; }
    public string? PP_bulk_mass_u_m { get; }
    public decimal PP_ream_mass { get; }
    public string? PP_ream_mass_u_m { get; }
    public int PP_grade { get; }
    public byte PP_abnormal_size { get; }
    public string? PP_paper_mass_basis { get; }
    public byte charge_item { get; }
    public short pull_up_safety_stock_rule { get; }
    public double pull_up_safety_stock_value { get; }
    public string? commodity_jurisdiction { get; }
    public string? eccn_usml_value { get; }
    public string? export_compliance_program { get; }
    public string? sched_b_num { get; }
    public string? hts_code { get; }
    public string? country { get; }
    public string? Uf_LRM_AssemblyType { get; }
    public string? Uf_LRM_CountryOfOrigin { get; }
    public string? Uf_LRM_Eccn { get; }
    public string? Uf_LRM_HSTariff { get; }
    public byte Uf_LRM_IsShipped { get; }
    public string? Uf_LRM_NetCost { get; }
    public string? Uf_LRM_NMFC { get; }
    public string? Uf_LRM_NMFCSub { get; }
    public string? Uf_LRM_PrefCriterion { get; }
    public string? Uf_LRM_Producer { get; }
    public int Uf_LRM_ProductAllocationMethod { get; }
    public string? Uf_LRM_UPCCode { get; }
    public byte Uf_WholeGoods { get; }
    public byte Uf_Item_Not_Sellable { get; }
    public string? Uf_FreightClass { get; }
    public byte Uf_Prelim { get; }
    public byte Uf_WebItem { get; }
    public byte fcst_bom_supply_flag { get; }
    public byte allow_on_pick_list { get; }
    public string? CN_item_tax_category { get; }
    public byte auto_job_for_external_order { get; }
    public string? auto_create_for_config { get; }
    public byte auto_create_for_config_external_order { get; }
    public byte Uf_AmazonFlag { get; }
    public string? Uf_AmazonItem { get; }
    public byte Uf_HomeDepotFlag { get; }
    public string? Uf_HomeDepotItem { get; }
    public byte Uf_LowesFlag { get; }
    public string? Uf_LowesItem { get; }
    public byte Uf_TractorFlag { get; }
    public string? Uf_TractorItem { get; }
    public byte Uf_WalmartFlag { get; }
    public string? Uf_WalmartItem { get; }
    public byte Uf_ItmKent { get; }
    public int Uf_ComponentPalletQty { get; }
    public byte Uf_HDSupplyFlag { get; }
    public string? Uf_HDSupplyItem { get; }
    public byte Uf_TargetFlag { get; }
    public string? Uf_TargetItem { get; }
    public string? Uf_FactoryCode { get; }
    public string? Uf_ItemGroup { get; }
    public string? Uf_CommodityDesc { get; }
    public byte Uf_EcomFlag { get; }
    public byte taxed_matl { get; }
    public decimal length { get; }
    public decimal width { get; }
    public decimal height { get; }
    public string? dimension_u_m { get; }
    public string? package_type { get; }
    public decimal package_type_max_qty { get; }
    public byte hazard { get; }
    public string? shipping_name { get; }
    public string? un_num { get; }
    public string? hazardous_matl_package_group { get; }
    public string? hazardous_matl_class { get; }
    public string? hazmat_contact { get; }
    public string? hazmat_contact_phone { get; }
    public byte hazmat_placard_required { get; }
    public string? national_motor_freight_class { get; }
    public string? freight_class { get; }
    public byte Uf_ReplacementPart { get; }
    public byte Uf_ChapinLabel { get; }
    public byte Uf_PrivateLabel { get; }
    public byte Uf_CheckSafetyStock { get; }
    public string? Uf_SlowMovingNote { get; }
}
